blog/urls.py
from django.urls import path
from . import views

app_name='blog'

urlpatterns=[
    path("",views.index),
    path('post/<slug:slug>',views.detail,name='detail'),

    # Redirection Pages 
    # path('new_url',views.new_url,name="newpage"),
    # path('old_url',views.old_url,name="oldpage"),

    path('contact',views.contact_view,name='contact'),
    path('about',views.about_page,name='about'),
]

myapp/urls.py
from django.contrib import admin
from django.urls import path , include

handler404 = 'myapp.views.custom_page_not_found'

urlpatterns = [
    path('',include("blog.urls")),
    path('admin/', admin.site.urls),   
]

blog/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.

# Category Model
class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    

# Post Model
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    img_url = models.URLField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)

    def save(self,*args,**kwargs):
        self.slug=slugify(self.title)
        super().save(*args,**kwargs)

    def __str__(self):
        return self.title
    
class About(models.Model):
    content = models.TextField()

blog/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(label='Name',max_length=100,required=True)
    email = forms.EmailField(label='Email',required=True)
    message = forms.CharField(label='Message', required=True)

blog/views.py
from django.shortcuts import render , redirect , get_object_or_404
from django.http import HttpResponse
from django.urls import reverse
import logging
from .models import Post,About
from django.core.paginator import Paginator
from .forms import ContactForm

# TESTING Purpose
logger = logging.getLogger("TESTING")

# Create your views here.

def index(request):

    # getting data from post model
    posts = Post.objects.all()
    
    # Pagination
    paginator = Paginator(posts,5)
    page_num = request.GET.get('page')
    page_obj = paginator.get_page(page_num)

    return render(request,'blog/index.html',{'page_obj':page_obj})

def detail(request,slug):
     post = get_object_or_404(Post, slug=slug)
     related_posts = Post.objects.filter(category = post.category).exclude(pk=post.id)[:5]
     return render(request,'blog/detail.html',{'post':post,'related_posts':related_posts})

def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')
        if form.is_valid():
            logger.debug(f'POST Data is {form.cleaned_data['name']} {form.cleaned_data['email']} {form.cleaned_data['message']}')                
            success_message = 'Your Email has been sent!'
            return render(request,'blog/contact.html',{'form':form,'success_message':success_message})

        else:
            logger.debug('Form Validation Error')
        return render(request,'blog/contact.html',{'form':form,'name':name,'email':email,'message':message})     
    return render(request,'blog/contact.html')

def about_page(request):
    about_content = About.objects.first().content
    return render(request,'blog/about.html',{'about_content':about_content})

# Redirection Pages
# def old_url(request):
#     return redirect(reverse('blog:newpage'))

# def new_url(request):
#     return HttpResponse("New Page is here")

myapp/views.py
from django.shortcuts import render

def custom_page_not_found(request,exception):
    return render(request,'404.html',status=404)

blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="container-fluid ">
        <h3>About Us</h3>
        <div class="d-flex gap-3 justify-content-center mt-5">
            <img src="https://picsum.photos/300/300" alt="">
            <div class="content">
               {{about_content}}
            </div>            
        </div>
    </div>
{% endblock %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{blogTitle}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
</head>
<body class="d-flex flex-column min-vh-100">

    <!-- Header -->
    {% include 'blog/includes/header.html' %}
    
    <!-- Dynamic Content -->
     <main class="flex-fill">
     {% block content %}
     {% endblock %}
     </main>

    <!-- Footer -->
    {% include 'blog/includes/footer.html' %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/contact.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="container-fluid ">
        <div class="d-flex justify-content-center mt-5">
            <div class="d-flex gap-3 flex-column">
                <h3>Contact Form</h3>
                <!-- Error Message -->
                {% for field in form %}
                     {% if field.errors %}
                         <div class="col-12">
                            <span class='fw-bold'>{{field.label_tag}}</span>
                            {% for error in field.errors %} 
                            <span class='text-danger'>{{error}}</span>
                            {% endfor %}
                         </div>
                     {% endif %}
                {% endfor %}

                <!--Success Message-->
                {% if success_message %}
                <div class="alert alert-success" role="alert">
                    {{success_message}}
                </div>
            
                {% endif %}
                <form method="post" class="row g-3">
                    {% csrf_token %}
                    <div class="col-md-6">
                        <label for="name" class="form-label">Name</label>
                        <input type="text" class="form-control" id="name" name="name" value="{{name}}">
                    </div>
                    <div class="col-md-6">
                        <label for="email" class="form-label">Email</label>
                        <input type="email" class="form-control" id="email" name="email" value="{{email}}">
                    </div>
                    <div class="col-12">
                        <label for="message" class="form-label">Message</label>
                        <textarea class="form-control" id="message" name="message" rows="4" value="{{message}}"></textarea>
                    </div>
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
        
    </div>
{% endblock %}

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="container-fluid ">
       
        <div class="row">
            <div class="col-lg-8">
              <h1 class="mb-4">{{post.title}} <small style="font-size:18px">({{post.category.name}})</small></h1>
              <p class="text-muted">Posted on {{post.created_at | date:"F j,Y"}}</p>
              <img src="{{post.img_url}}" class="img-fluid mb-4" alt="Blog Image">
              <p>{{post.content}}</p>
            </div>
            <div class="col-lg-4">
              <div class="card mt-3">
                <div class="card-body">
                  <h5 class="card-title">Related Posts</h5>
                  <ul class="list-unstyled">
                    {% for related_post in related_posts %}
                    <li><a href="{% url 'blog:detail' slug=related_post.slug %}">{{related_post.title}}</a></li><br>
                    {% empty %}
                    <p>No related posts found.</p>
                    {% endfor %}
                  </ul>
                </div>
              </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/includes/footer.html
<footer class="bg-dark text-light p-3 text-center">
    <span>© 2026 Company, Inc</span>
</footer>

blog/templates/blog/includes/header.html
<header class="p-3 bg-dark text-white">
    <div class="d-flex justify-content-between align-items-center">
        
        
        <a class="text-light text-decoration-none" href="/blog">
            <h3 class="m-0">Blog</h3>
        </a>

        
        <div class="d-flex gap-3">
            <a class="text-light text-decoration-none" href="/">Home</a>
            <a class="text-light text-decoration-none" href="/about">About</a>
            <a class="text-light text-decoration-none" href="/contact">Contact</a>
        </div>

    </div>
</header>

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="container-fluid ">
        <div class="row">
            <h2 >Latest Posts</h2>
        </div>

        <div class="row m-3">
            {% if page_obj %}
            {% for post in page_obj %}
            <div class="col-4 mb-4">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4">
                                <img src={{post.img_url}} class="img-fluid" alt="...">
                            </div>
                            <div class="col-md-8">
                                <h5 class="card-title">{{post.title}}</h5>
                                <p class="card-text">{{post.content | truncatechars:50}}</p>
                                <div class="d-flex justify-content-between">
                                     <a href="{% url 'blog:detail' slug=post.slug %}">Read More</a>
                                    <a class="text-decoration-none text-dark fw-bold" href="#">{{post.category.name}}</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
             <div class="col-12 my-3">
                {% if page_obj.has_other_pages %}
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page=1" aria-label="First">
                                <span aria-hidden="true">&laquo; first</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                                <span aria-hidden="true">previous</span>
                            </a>
                        {% endif %}    
                        </li>
                        <li class="page-item"><span class="page-link">Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}.</span></li>
                        {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                                <span aria-hidden="true">next</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{page_obj.paginator.num_pages}}" aria-label="Last">
                                <span aria-hidden="true">last &raquo;</span>
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>     
                {% endif %}    
            </div>
       
       {% else %}
       <p>No Posts Available!</p>
       {% endif %}

 {% endblock %}   